### ISSUE TITLE
Error when running Gekko

### ISSUE THREAD

**Issue by B41LSY** [RJPGriffin/google-forms-gekko-plugin#1]
Hi, i'm getting this error when trying to run Gekko, very new to this so not entirely sure what i'm doing lol.

Here's the error msg i'm getting:

C:\Users\Ballsy\gekko\plugins.js:197
        description: 'Logs Trades to Google Forms',
                   ^

SyntaxError: Unexpected token :
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at pipeline (C:\Users\Ballsy\gekko\core\pipeline.js:42:26)
  xxx POST /api/backtest 500 3,650ms -

  Error: non-error thrown: Child process has died.
      at Object.onerror (C:\Users\Ballsy\gekko\node_modules\koa\lib\c
05:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by RJPGriffin** [comment]
It looks like that's going to be an error in the plugins.js where you added the gforms object - could you post a copy of the gforms section of that file, as well as a few lines before and after?

**Comment by B41LSY** [comment]
I've fixed it, was a daft formatting error. If i run Gekko via the UI will it update the sheet with papertrading or does it only work via the CLI?

Thanks for the very quick response :-)

**Comment by RJPGriffin** [comment]
Glad you've fixed it :)

I have added some commits just before you messaged, so you had me worried! (if you're just starting out, grab the new files now - they add slippage against advice price calculation to the sheet.)

Only works via the CLI - don't think you can load any plugins through the ui...
